name: deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run build
      - run: ls
      # - run: ssh -i "$EC2KEY" ubuntu@ec2-54-254-221-15.ap-southeast-1.compute.amazonaws.com
      - run: scp -i ${{ secrets.EC2KEY }} dist/ ubuntu@ec2-54-254-221-15.ap-southeast-1.compute.amazonaws.com 

